// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
// eslint-disable-next-line ts/no-empty-object-type
interface CloudflareBindings {
}
